# Generated by Django 3.0.4 on 2020-06-09 18:51

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventSuggestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250, null=True)),
                ('header_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('content', ckeditor.fields.RichTextField()),
                ('pdf', models.URLField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='KodaDiaries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250, null=True)),
                ('header_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('content', ckeditor.fields.RichTextField()),
                ('author', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SuggestedSources',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250, null=True)),
                ('header_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('youtube_url', models.URLField(blank=True, max_length=250, null=True)),
                ('pdf', models.URLField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TgpAdvantures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250, null=True)),
                ('youtube_url', models.URLField(blank=True, max_length=250, null=True)),
                ('pdf', models.URLField(blank=True, max_length=250, null=True)),
                ('mp3', models.URLField(blank=True, max_length=250, null=True)),
            ],
        ),
    ]
