# Generated by Django 3.0.4 on 2020-06-09 19:24

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('koda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventsuggestions',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kodadiaries',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
