# Generated by Django 2.2.14 on 2021-01-30 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('koda', '0002_auto_20210130_1504'),
    ]

    operations = [
        migrations.DeleteModel(
            name='KVKKForms',
        ),
    ]
