# Generated by Django 3.0.4 on 2020-06-09 20:06

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('koda', '0002_auto_20200609_1924'),
    ]

    operations = [
        migrations.CreateModel(
            name='RemoteLearning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250, null=True)),
                ('header_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('header_title', models.CharField(blank=True, max_length=250, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('pdf', models.URLField(blank=True, max_length=250, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='TeachersDocuments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250, null=True)),
                ('header_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('header_content', models.CharField(blank=True, max_length=250, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('pdf', models.URLField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='eventsuggestions',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
