# Generated by Django 3.0.4 on 2020-06-10 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('koda', '0003_auto_20200609_2006'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuggestedSitesType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='SuggestedSites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('url', models.URLField()),
                ('site_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='koda.SuggestedSitesType')),
            ],
        ),
    ]
