# Generated by Django 2.2.14 on 2021-01-30 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('koda', '0004_kvkkforms'),
    ]

    operations = [
        migrations.DeleteModel(
            name='KVKKForms',
        ),
    ]
