# Generated by Django 3.0.4 on 2020-06-13 16:58

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('koda', '0004_suggestedsites_suggestedsitestype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kodadiaries',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
