# Generated by Django 2.2.14 on 2021-01-31 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('koda', '0007_kodateam'),
    ]

    operations = [
        migrations.DeleteModel(
            name='KVKKForm',
        ),
    ]
