# Generated by Django 2.2.14 on 2021-02-06 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('koda', '0010_auto_20210206_1303'),
    ]

    operations = [
        migrations.CreateModel(
            name='Covid19Information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('content', models.CharField(max_length=500)),
                ('pdf', models.FileField(upload_to='')),
            ],
        ),
    ]
