# Generated by Django 2.2.14 on 2021-02-16 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('koda', '0012_kodaconsultants_kodatrainers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kodaconsultants',
            name='email',
        ),
        migrations.RemoveField(
            model_name='kodatrainers',
            name='email',
        ),
    ]
