# Generated by Django 2.2.14 on 2021-02-18 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('koda', '0014_ogretmentopluluklariyorumlari'),
    ]

    operations = [
        migrations.CreateModel(
            name='KoyeİlkAdimYorumlari',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=1000)),
                ('image', models.ImageField(blank=True, null=True, upload_to='koye-ilk-adim-yorumlari')),
            ],
        ),
    ]
