# Generated by Django 2.2.14 on 2021-02-18 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('koda', '0015_koyei̇lkadimyorumlari'),
    ]

    operations = [
        migrations.CreateModel(
            name='KoyeİlkAdimVideolar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('youtube_url', models.CharField(max_length=1000)),
                ('type', models.IntegerField(choices=[(1, 'Deneyim'), (2, 'Eğitim'), (3, 'Atölye')])),
            ],
        ),
    ]
