# Generated by Django 2.2.14 on 2021-02-18 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('koda', '0016_koyei̇lkadimvideolar'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Covid19Information',
            new_name='BiaIcerikler',
        ),
    ]
