# Generated by Django 2.2.14 on 2021-02-20 15:51

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('koda', '0017_auto_20210218_2014'),
    ]

    operations = [
        migrations.CreateModel(
            name='GecmisFaaliyetler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
            ],
        ),
    ]
