# Generated by Django 2.2.14 on 2021-02-24 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('koda', '0018_gecmisfaaliyetler'),
    ]

    operations = [
        migrations.CreateModel(
            name='StratejikPlanVeMaliBelgeler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf', models.FileField(upload_to='')),
                ('type', models.IntegerField(choices=[(1, 'Stratejik Plan'), (2, 'Bağımsız Denetim Raporları'), (3, 'İç Denetim Raporları'), (4, 'Gelir- Gider Tabloları'), (5, 'Beyannameler')])),
            ],
        ),
        migrations.CreateModel(
            name='Yayinlarimiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('pdf', models.FileField(upload_to='')),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
