# Generated by Django 3.1 on 2021-06-13 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('koda', '0021_auto_20210613_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='header_image',
            field=models.ImageField(default=1, upload_to='blog'),
            preserve_default=False,
        ),
    ]
